"""
science/research_plan.py
ResearchPlan — the object that makes the system behave like a scientific analyst.

A ResearchPlan contains:
  - hypotheses (generated by hypothesis jury)
  - feasibility assessments (generated by feasibility agent)
  - test assignments (which analysis agents test which hypothesis)
  - evidence slots (filled in as agents run)
  - verdicts (closed by ConclusionEngine)

This object lives in AnalysisContext and is the structural backbone of
hypothesis-driven reasoning. Without it, analysis is reactive.
With it, every agent run is evidence for or against a specific claim.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class HypothesisStatus(str, Enum):
    PENDING     = "pending"
    TESTABLE    = "testable"
    NOT_TESTABLE = "not_testable"
    CONFIRMED   = "confirmed"
    REJECTED    = "rejected"
    INCONCLUSIVE = "inconclusive"


@dataclass
class Hypothesis:
    id: str
    statement: str
    source: str          # "data" | "business" | "web" | "prior"
    novelty_score: float = 1.0    # 0=seen before, 1=novel
    status: HypothesisStatus = HypothesisStatus.PENDING
    testable: bool | None = None
    missing_data: list[str] = field(default_factory=list)   # what data is needed
    assigned_agents: list[str] = field(default_factory=list)
    evidence: list[dict] = field(default_factory=list)      # filled by agents
    verdict: str = ""
    confidence: float = 0.0
    evidence_state: str = "untouched"
    evidence_grade: str = "unknown"
    uncertainty_level: str = "unknown"
    supporting_evidence_count: int = 0
    opposing_evidence_count: int = 0


@dataclass
class ResearchPlan:
    """
    Moves through the pipeline from hypothesis generation → conclusion.
    Every agent that runs adds evidence to relevant hypotheses.
    """
    hypotheses: list[Hypothesis] = field(default_factory=list)
    data_gaps: list[str] = field(default_factory=list)
    conclusions: list[dict] = field(default_factory=list)
    primary_conclusion: str = ""
    experiment_spec: Any = None      # v0.6: ExperimentSpec proposed for inconclusive hypotheses
    overall_confidence: float = 0.0

    # ------------------------------------------------------------------
    # Hypothesis management
    # ------------------------------------------------------------------

    def add_hypothesis(self, h: Hypothesis):
        # Penalise novelty for near-duplicate statements
        existing = [x.statement.lower() for x in self.hypotheses]
        if any(self._similarity(h.statement.lower(), e) > 0.7 for e in existing):
            h.novelty_score *= 0.3
        self.hypotheses.append(h)

    def testable_hypotheses(self) -> list[Hypothesis]:
        return [h for h in self.hypotheses if h.status == HypothesisStatus.TESTABLE]

    def add_evidence(self, hypothesis_id: str, evidence: dict):
        for h in self.hypotheses:
            if h.id == hypothesis_id:
                h.evidence.append(evidence)
                if evidence.get("supports"):
                    h.supporting_evidence_count += 1
                else:
                    h.opposing_evidence_count += 1
                break

    def add_data_gap(self, gap: str):
        if gap not in self.data_gaps:
            self.data_gaps.append(gap)

    def ranked_hypotheses(self) -> list[Hypothesis]:
        """Sorted by confidence descending, then novelty."""
        return sorted(
            [h for h in self.hypotheses if h.status != HypothesisStatus.PENDING],
            key=lambda h: (h.confidence, h.novelty_score),
            reverse=True,
        )

    def summary_for_brief(self) -> str:
        lines = []
        for h in self.ranked_hypotheses():
            icon = {
                HypothesisStatus.CONFIRMED:    "CONFIRMED",
                HypothesisStatus.REJECTED:     "REJECTED",
                HypothesisStatus.INCONCLUSIVE: "INCONCLUSIVE",
                HypothesisStatus.NOT_TESTABLE: "NOT TESTABLE",
            }.get(h.status, h.status.value.upper())
            lines.append(
                f"{icon} (conf={h.confidence:.2f}, grade={h.evidence_grade}, uncertainty={h.uncertainty_level}): {h.statement}"
            )
            if h.missing_data:
                lines.append(f"  → Data needed: {', '.join(h.missing_data)}")
            if h.verdict:
                lines.append(f"  → {h.verdict}")
        if self.data_gaps:
            lines.append(f"\nData gaps identified: {', '.join(self.data_gaps)}")
        return "\n".join(lines)

    @staticmethod
    def _similarity(a: str, b: str) -> float:
        """Simple word-overlap similarity."""
        words_a = set(a.split())
        words_b = set(b.split())
        if not words_a or not words_b:
            return 0.0
        return len(words_a & words_b) / len(words_a | words_b)
